services:
  task-service-app-backend:
    container_name: task-service
    image: task-service
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    networks:
      - task-service

networks:
  task-service:
    driver: bridge