services:
  auth-app-backend:
    container_name: auth-app-backend
    image: auth-app-backend
    build:
      context: ..
      dockerfile: Dockerfile
    command: "gunicorn --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 --timeout 120 --log-level info app.main:create_app"
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    depends_on:
      - mongo
      - cache
    networks:
      - auth

networks:
  auth:
    driver: bridge