services:
  user-service-app-backend:
    container_name: user-service-app-backend
    image: user-service-app-backend
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    networks:
      - user-service

networks:
  user-service:
    driver: bridge